"""Initial schema

Revision ID: 001
Revises:
Create Date: 2024-01-01 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('username', sa.String(length=50), nullable=False),
        sa.Column('email', sa.String(length=100), nullable=False),
        sa.Column('hashed_password', sa.String(length=255), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)

    op.create_table('user_profiles',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('experience_level', sa.Enum('NOVICE', 'INTERMEDIATE', 'EXPERT', name='experiencelevel'), nullable=False),
        sa.Column('holding_horizon', sa.Enum('SHORT', 'MEDIUM', 'LONG', name='holdinghorizon'), nullable=False),
        sa.Column('risk_tolerance', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='risktolerance'), nullable=False),
        sa.Column('behavior_tags', sa.JSON(), nullable=True),
        sa.Column('investment_goals', sa.String(length=255), nullable=True),
        sa.Column('portfolio_size', sa.String(length=50), nullable=True),
        sa.Column('preferred_sectors', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_id'), 'user_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=False)

    op.create_table('stocks',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('stock_id', sa.String(length=20), nullable=False),
        sa.Column('stock_name', sa.String(length=100), nullable=False),
        sa.Column('market', sa.String(length=10), nullable=False),
        sa.Column('industry', sa.String(length=100), nullable=True),
        sa.Column('listing_date', sa.String(length=20), nullable=True),
        sa.Column('total_shares', sa.Float(), nullable=True),
        sa.Column('float_shares', sa.Float(), nullable=True),
        sa.Column('pe_ratio', sa.Float(), nullable=True),
        sa.Column('pb_ratio', sa.Float(), nullable=True),
        sa.Column('dividend_yield', sa.Float(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stocks_id'), 'stocks', ['id'], unique=False)
    op.create_index(op.f('ix_stocks_stock_id'), 'stocks', ['stock_id'], unique=True)

    op.create_table('analyses',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('stock_id', sa.String(length=20), nullable=False),
        sa.Column('scenario', sa.Enum('single_stock_check', 'pre_trade_check', 'post_trade_review', name='interactionscenario'), nullable=False),
        sa.Column('status', sa.Enum('PROCESSING', 'READY', 'EXPIRED', 'FAILED', name='analysisstatus'), nullable=False),
        sa.Column('headline', sa.String(length=255), nullable=True),
        sa.Column('scenario_payload', sa.JSON(), nullable=True),
        sa.Column('decision_card', sa.JSON(), nullable=True),
        sa.Column('fit_summary', sa.Text(), nullable=True),
        sa.Column('market_context', sa.JSON(), nullable=True),
        sa.Column('explanation_layer', sa.JSON(), nullable=True),
        sa.Column('intervention', sa.JSON(), nullable=True),
        sa.Column('review_at', sa.DateTime(), nullable=True),
        sa.Column('valid_until', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyses_id'), 'analyses', ['id'], unique=False)
    op.create_index(op.f('ix_analyses_stock_id'), 'analyses', ['stock_id'], unique=False)
    op.create_index(op.f('ix_analyses_user_id'), 'analyses', ['user_id'], unique=False)

    op.create_table('analysis_reasons',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('analysis_id', sa.Integer(), nullable=False),
        sa.Column('text', sa.Text(), nullable=False),
        sa.Column('order', sa.Integer(), nullable=False),
        sa.Column('mark_type', sa.Enum('DATA_FACT', 'MODEL_INFERENCE', 'UNCERTAINTY', name='outputmarktype'), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_reasons_analysis_id'), 'analysis_reasons', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_analysis_reasons_id'), 'analysis_reasons', ['id'], unique=False)

    op.create_table('review_tasks',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('analysis_id', sa.Integer(), nullable=False),
        sa.Column('stock_name', sa.String(length=100), nullable=False),
        sa.Column('scenario', sa.String(length=50), nullable=False),
        sa.Column('review_at', sa.DateTime(), nullable=False),
        sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'EXPIRED', name='reviewtaskstatus'), nullable=False),
        sa.Column('review_result', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_tasks_analysis_id'), 'review_tasks', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_review_tasks_id'), 'review_tasks', ['id'], unique=False)
    op.create_index(op.f('ix_review_tasks_user_id'), 'review_tasks', ['user_id'], unique=False)

    op.create_table('watchlist_items',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('stock_id', sa.String(length=20), nullable=False),
        sa.Column('focus_reason', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlist_items_id'), 'watchlist_items', ['id'], unique=False)
    op.create_index(op.f('ix_watchlist_items_stock_id'), 'watchlist_items', ['stock_id'], unique=False)
    op.create_index(op.f('ix_watchlist_items_user_id'), 'watchlist_items', ['user_id'], unique=False)

    op.create_table('focus_reasons',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('analysis_id', sa.Integer(), nullable=False),
        sa.Column('stock_id', sa.String(length=20), nullable=False),
        sa.Column('reason', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_focus_reasons_analysis_id'), 'focus_reasons', ['analysis_id'], unique=False)
    op.create_index(op.f('ix_focus_reasons_id'), 'focus_reasons', ['id'], unique=False)
    op.create_index(op.f('ix_focus_reasons_stock_id'), 'focus_reasons', ['stock_id'], unique=False)
    op.create_index(op.f('ix_focus_reasons_user_id'), 'focus_reasons', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_focus_reasons_user_id'), table_name='focus_reasons')
    op.drop_index(op.f('ix_focus_reasons_stock_id'), table_name='focus_reasons')
    op.drop_index(op.f('ix_focus_reasons_id'), table_name='focus_reasons')
    op.drop_index(op.f('ix_focus_reasons_analysis_id'), table_name='focus_reasons')
    op.drop_table('focus_reasons')

    op.drop_index(op.f('ix_watchlist_items_user_id'), table_name='watchlist_items')
    op.drop_index(op.f('ix_watchlist_items_stock_id'), table_name='watchlist_items')
    op.drop_index(op.f('ix_watchlist_items_id'), table_name='watchlist_items')
    op.drop_table('watchlist_items')

    op.drop_index(op.f('ix_review_tasks_user_id'), table_name='review_tasks')
    op.drop_index(op.f('ix_review_tasks_id'), table_name='review_tasks')
    op.drop_index(op.f('ix_review_tasks_analysis_id'), table_name='review_tasks')
    op.drop_table('review_tasks')

    op.drop_index(op.f('ix_analysis_reasons_id'), table_name='analysis_reasons')
    op.drop_index(op.f('ix_analysis_reasons_analysis_id'), table_name='analysis_reasons')
    op.drop_table('analysis_reasons')

    op.drop_index(op.f('ix_analyses_user_id'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_stock_id'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_id'), table_name='analyses')
    op.drop_table('analyses')

    op.drop_index(op.f('ix_stocks_stock_id'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_id'), table_name='stocks')
    op.drop_table('stocks')

    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_profiles_id'), table_name='user_profiles')
    op.drop_table('user_profiles')

    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')

    # Drop enums
    op.execute("DROP TYPE IF EXISTS experiencelevel")
    op.execute("DROP TYPE IF EXISTS holdinghorizon")
    op.execute("DROP TYPE IF EXISTS risktolerance")
    op.execute("DROP TYPE IF EXISTS interactionscenario")
    op.execute("DROP TYPE IF EXISTS analysisstatus")
    op.execute("DROP TYPE IF EXISTS outputmarktype")
    op.execute("DROP TYPE IF EXISTS reviewtaskstatus")
    # ### end Alembic commands ###
